# 全局配置
HttpPort = 3001 # HTTP 监听的端口号
Mode = "produce" # 运行模式 dev=开发模式 (日志debug调整) produce=生产模式
FrontEnd = ["*"] # 跨域白名单

#日志
[Log]
    Dir = "/log" #日志写入目录

# 文件配置
[Upload]
    Host = "" # 文件host地址
    Dir = "/data/resources/tousu/upload" #文件上传目录

# 数据库配置
[Mysql]
    State = 0 # 开关 0=关闭 1=开启
    Host = "192.168.2.222"
    Database = "xmt"
    UserName = "root"
    Password = "Ezsv9499"
    Port = 3306
    MaxIdleConns = 1000 # 用于设置闲置的连接数
    MaxOpenConns = 3000 # 用于设置最大打开的连接数，默认值为0表示不限制

# redis配置
[Redis]
    State = 0 # 开关 0=关闭 1=开启
    Host = "192.168.2.222"
    Password = ""
    Port = "6701"
    MaxIdle = 1000
    MaxActive = 0
    IdleTimeout = 300
    MaxTimeout = 30



